version: '2'
services:

  nginx:
    image: nginx:1.11.8-alpine
    container_name: nginx
    ports:
    - "80:80"
    - "443:443"
    volumes:
    - ./http/index.html:/usr/share/nginx/html/index.html
    - ./http/site.conf:/etc/nginx/conf.d/default.conf
    - ./http/nginx.crt:/etc/nginx/nginx.crt
    - ./http/nginx.key:/etc/nginx/nginx.key

